### ISSUE TITLE
Build fails due to undefined: syscall.Syscall

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/buildkiteport#5]
# github.com/creack/pty
pty/ioctl_inner.go:15:21: undefined: syscall.Syscall

Is this a known issue @v1gnesh ?

**Comment by v1gnesh** [comment]
Is this from a manual build or... ? Which version of BK?

**Comment by IgorTodorovskiIBM** [comment]
Manual and in Jenkins. I realized it's because the pty patch is not being applied:
```

Cloning into 'pty'...
Checking out v1.1.21
HEAD is now at f188b6d Revert go.mod for v1.
error: can't open patch '../deps-patches/pty--v1.1.21.patch': EDC5129I No such file or directory.
```

Looks like it was deleted in https://github.com/ZOSOpenTools/buildkiteport/commit/d4ecc36041bee5a7316efc3d4f520cfebaaea37d . Should it be deleted?

**Comment by v1gnesh** [comment]
Ah right.

I deleted local copies of patches after starting to accumulate them in wharf under deps-patches.
Updated buildenv to pull from there - https://github.com/ZOSOpenTools/buildkiteport/commit/8773a710224330dfa8f76a504818a31adb4403ab

**Comment by IgorTodorovskiIBM** [comment]
great! thank you
